from scrapy import Item, Field

class WebmdItem(Item):
    Drug = Field()
    Indication = Field()
    Type = Field()
    Review = Field()
    Condition = Field()
    Use = Field()
    HowtoUse = Field()
    Sides = Field()
    Precautions = Field()
    Interactions = Field()
    GenName = Field()
    BrandName = Field()
    AvoidUse = Field()
    Allergies = Field()
    Satisfaction = Field()
    EaseofUse = Field()
    Effectiveness = Field()
    EstimatedPrice = Field()
    Dosage = Field()
    Form = Field()
    PkgCount = Field()
